enum ItemType {
  Undefined = 'Undefined',
  HeadArmor = 'HeadArmor',
  ShoulderArmor = 'ShoulderArmor',
  BodyArmor = 'BodyArmor',
  HandArmor = 'HandArmor',
  LegArmor = 'LegArmor',
  MountHarness = 'MountHarness',
  Mount = 'Mount',
  Shield = 'Shield',
  Bow = 'Bow',
  Crossbow = 'Crossbow',
  OneHandedWeapon = 'OneHandedWeapon',
  TwoHandedWeapon = 'TwoHandedWeapon',
  Polearm = 'Polearm',
  Thrown = 'Thrown',
  Arrows = 'Arrows',
  Bolts = 'Bolts',
  Pistol = 'Pistol',
  Musket = 'Musket',
  Bullets = 'Bullets',
  Banner = 'Banner',
}

export default ItemType;
