export const Longsword = {
  id: 'crpg_sentinel_2hsword_abearirl',
  baseId: 'crpg_sentinel_2hsword_abearirl',
  createdAt: '2023-05-13T21:43:44.0741909Z',
  rank: 0,
  name: 'Longsword',
  culture: 'Neutral',
  type: 'TwoHandedWeapon',
  price: 14117,
  tier: 10.046391,
  requirement: 0,
  weight: 2.17,
  flags: ['Civilian'],
  armor: null,
  mount: null,
  weapons: [
    {
      class: 'OneHandedSword',
      itemUsage: 'onehanded_block_rshield_swing_thrust',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 107,
      balance: 0.2,
      handling: 64,
      bodyArmor: 5,
      flags: ['MeleeWeapon'],
      thrustDamage: 19,
      thrustDamageType: 'Pierce',
      thrustSpeed: 84,
      swingDamage: 39,
      swingDamageType: 'Cut',
      swingSpeed: 75,
    },
    {
      class: 'TwoHandedSword',
      itemUsage: 'twohanded_block_swing_thrust',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 107,
      balance: 0.79,
      handling: 76,
      bodyArmor: 5,
      flags: ['MeleeWeapon', 'NotUsableWithOneHand'],
      thrustDamage: 19,
      thrustDamageType: 'Pierce',
      thrustSpeed: 91,
      swingDamage: 39,
      swingDamageType: 'Cut',
      swingSpeed: 93,
    },
    {
      class: 'OneHandedSword',
      itemUsage: 'onehanded_block_swing_thrust',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 107,
      balance: 0.2,
      handling: 64,
      bodyArmor: 5,
      flags: ['MeleeWeapon'],
      thrustDamage: 19,
      thrustDamageType: 'Pierce',
      thrustSpeed: 84,
      swingDamage: 39,
      swingDamageType: 'Cut',
      swingSpeed: 75,
    },
  ],
};

export const WoodenSword = {
  id: 'crpg_wooden_sword_t1',
  baseId: 'crpg_wooden_sword_t1',
  createdAt: '2023-07-13T21:43:44.0741909Z',
  rank: 0,
  name: 'Wooden Sword',
  culture: 'Neutral',
  type: 'OneHandedWeapon',
  price: 257,
  tier: 1.0245335,
  requirement: 0,
  weight: 1.42,
  flags: [],
  armor: null,
  mount: null,
  weapons: [
    {
      class: 'OneHandedSword',
      itemUsage: 'onehanded_block_shield_swing_thrust',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 95,
      balance: 0.75,
      handling: 95,
      bodyArmor: 1,
      flags: ['MeleeWeapon', 'NoBlood'],
      thrustDamage: 10,
      thrustDamageType: 'Blunt',
      thrustSpeed: 92,
      swingDamage: 10,
      swingDamageType: 'Blunt',
      swingSpeed: 92,
    },
  ],
};

export const NobleCavalryLance = {
  id: 'crpg_khuzait_lance_3_t5',
  baseId: 'crpg_khuzait_lance_3_t5',
  createdAt: '2023-07-13T21:43:44.0741909Z',
  rank: 0,
  name: 'Noble Cavalry Lance',
  culture: 'Khuzait',
  type: 'Polearm',
  price: 2593,
  tier: 3.7166684,
  requirement: 0,
  weight: 2.03,
  flags: ['NotStackable'],
  armor: null,
  mount: null,
  weapons: [
    {
      class: 'OneHandedPolearm',
      itemUsage: 'onehanded_polearm_block_long_rshield_thrust',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 200,
      balance: 0,
      handling: 62,
      bodyArmor: 0,
      flags: ['MeleeWeapon', 'WideGrip'],
      thrustDamage: 25,
      thrustDamageType: 'Pierce',
      thrustSpeed: 82,
      swingDamage: 0,
      swingDamageType: 'Undefined',
      swingSpeed: 18,
    },
    {
      class: 'TwoHandedPolearm',
      itemUsage: 'polearm_block_long_shield_thrust',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 200,
      balance: 0,
      handling: 58,
      bodyArmor: 0,
      flags: ['MeleeWeapon', 'NotUsableWithOneHand', 'WideGrip', 'TwoHandIdleOnMount'],
      thrustDamage: 25,
      thrustDamageType: 'Pierce',
      thrustSpeed: 91,
      swingDamage: 0,
      swingDamageType: 'Undefined',
      swingSpeed: 68,
    },
    {
      class: 'TwoHandedPolearm',
      itemUsage: 'polearm_couch',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 200,
      balance: 0,
      handling: 62,
      bodyArmor: 0,
      flags: ['MeleeWeapon', 'WideGrip'],
      thrustDamage: 25,
      thrustDamageType: 'Pierce',
      thrustSpeed: 82,
      swingDamage: 0,
      swingDamageType: 'Undefined',
      swingSpeed: 18,
    },
  ],
};

export const BecDeCorbin = {
  id: 'crpg_bec_de_corbin',
  baseId: 'crpg_bec_de_corbin',
  createdAt: '2023-07-13T21:43:44.0741909Z',
  rank: 0,
  name: 'Bec De Corbin',
  culture: 'Neutral',
  type: 'Polearm',
  price: 14020,
  tier: 10.008125,
  requirement: 0,
  weight: 2.11,
  flags: ['CanBePickedUpFromCorpse'],
  armor: null,
  mount: null,
  weapons: [
    {
      class: 'TwoHandedPolearm',
      itemUsage: 'polearm_block_long_shield_swing_thrust',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 139,
      balance: 0.4,
      handling: 70,
      bodyArmor: 0,
      flags: ['MeleeWeapon', 'NotUsableWithOneHand', 'WideGrip', 'TwoHandIdleOnMount'],
      thrustDamage: 27,
      thrustDamageType: 'Pierce',
      thrustSpeed: 92,
      swingDamage: 29,
      swingDamageType: 'Pierce',
      swingSpeed: 82,
    },
  ],
};

export const SimpleShortSpear = {
  id: 'crpg_western_spear_2_t2',
  baseId: 'crpg_western_spear_2_t2',
  createdAt: '2023-07-13T21:43:44.0741909Z',
  rank: 0,
  name: 'Simple Short Spear',
  culture: 'Vlandia',
  type: 'Polearm',
  price: 1875,
  tier: 3.0168896,
  requirement: 0,
  weight: 1.08,
  flags: [],
  armor: null,
  mount: null,
  weapons: [
    {
      class: 'OneHandedPolearm',
      itemUsage: 'onehanded_polearm_block_long_rshield_thrust',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 156,
      balance: 0,
      handling: 72,
      bodyArmor: 0,
      flags: ['MeleeWeapon', 'WideGrip'],
      thrustDamage: 22,
      thrustDamageType: 'Pierce',
      thrustSpeed: 92,
      swingDamage: 16,
      swingDamageType: 'Blunt',
      swingSpeed: 49,
    },
    {
      class: 'TwoHandedPolearm',
      itemUsage: 'polearm_block_long_shield_swing_thrust',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 156,
      balance: 0.58,
      handling: 70,
      bodyArmor: 0,
      flags: ['MeleeWeapon', 'NotUsableWithOneHand', 'WideGrip', 'TwoHandIdleOnMount'],
      thrustDamage: 22,
      thrustDamageType: 'Pierce',
      thrustSpeed: 99,
      swingDamage: 16,
      swingDamageType: 'Blunt',
      swingSpeed: 87,
    },
    {
      class: 'TwoHandedPolearm',
      itemUsage: 'polearm_block_long_shield_thrust',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 156,
      balance: 0.58,
      handling: 70,
      bodyArmor: 0,
      flags: ['MeleeWeapon', 'NotUsableWithOneHand', 'WideGrip', 'TwoHandIdleOnMount'],
      thrustDamage: 22,
      thrustDamageType: 'Pierce',
      thrustSpeed: 99,
      swingDamage: 16,
      swingDamageType: 'Blunt',
      swingSpeed: 87,
    },
  ],
};

export const Pike = {
  id: 'crpg_vlandia_pike_1_t5',
  baseId: 'crpg_vlandia_pike_1_t5',
  createdAt: '2023-07-13T21:43:44.0741909Z',
  rank: 0,
  name: 'Pike',
  culture: 'Vlandia',
  type: 'Polearm',
  price: 3547,
  tier: 4.1352773,
  requirement: 0,
  weight: 1.07,
  flags: ['DropOnWeaponChange', 'TestFlag'],
  armor: null,
  mount: null,
  weapons: [
    {
      class: 'TwoHandedPolearm',
      itemUsage: 'polearm_pike',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 501,
      balance: 0,
      handling: 34,
      bodyArmor: 0,
      flags: ['MeleeWeapon', 'NotUsableWithOneHand', 'WideGrip', 'TwoHandIdleOnMount', 'TestFlag'],
      thrustDamage: 21,
      thrustDamageType: 'Pierce',
      thrustSpeed: 86,
      swingDamage: 0,
      swingDamageType: 'Undefined',
      swingSpeed: 22,
    },
    {
      class: 'TwoHandedPolearm',
      itemUsage: 'polearm_bracing',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 501,
      balance: 0,
      handling: 34,
      bodyArmor: 0,
      flags: ['MeleeWeapon', 'NotUsableWithOneHand', 'WideGrip', 'TwoHandIdleOnMount'],
      thrustDamage: 21,
      thrustDamageType: 'Pierce',
      thrustSpeed: 86,
      swingDamage: 0,
      swingDamageType: 'Undefined',
      swingSpeed: 22,
    },
  ],
};

export const Hoe = {
  id: 'crpg_peasant_2haxe_1_t1',
  baseId: 'crpg_peasant_2haxe_1_t1',
  createdAt: '2023-07-13T21:43:44.0741909Z',
  rank: 0,
  name: 'Hoe',
  culture: 'Neutral',
  type: 'TwoHandedWeapon',
  price: 677,
  tier: 1.462035,
  requirement: 0,
  weight: 1.27,
  flags: ['CanBePickedUpFromCorpse', 'Civilian'],
  armor: null,
  mount: null,
  weapons: [
    {
      class: 'OneHandedAxe',
      itemUsage: 'onehanded_rshield_axe',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 92,
      balance: 0.33,
      handling: 77,
      bodyArmor: 0,
      flags: ['MeleeWeapon', 'BonusAgainstShield'],
      thrustDamage: 0,
      thrustDamageType: 'Undefined',
      thrustSpeed: 92,
      swingDamage: 24,
      swingDamageType: 'Cut',
      swingSpeed: 79,
    },
    {
      class: 'TwoHandedAxe',
      itemUsage: 'twohanded_axe',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 92,
      balance: 0.88,
      handling: 85,
      bodyArmor: 0,
      flags: ['MeleeWeapon', 'NotUsableWithOneHand', 'BonusAgainstShield', 'TwoHandIdleOnMount'],
      thrustDamage: 0,
      thrustDamageType: 'Undefined',
      thrustSpeed: 99,
      swingDamage: 24,
      swingDamageType: 'Cut',
      swingSpeed: 96,
    },
    {
      class: 'OneHandedAxe',
      itemUsage: 'onehanded_axe',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 92,
      balance: 0.33,
      handling: 77,
      bodyArmor: 0,
      flags: ['MeleeWeapon', 'BonusAgainstShield'],
      thrustDamage: 0,
      thrustDamageType: 'Undefined',
      thrustSpeed: 92,
      swingDamage: 24,
      swingDamageType: 'Cut',
      swingSpeed: 79,
    },
  ],
};

export const Shield = {
  id: 'crpg_oval_shield',
  baseId: 'crpg_oval_shield',
  createdAt: '2023-07-13T21:43:44.0741909Z',
  rank: 0,
  name: 'Wooden Oval Shield',
  culture: 'Aserai',
  type: 'Shield',
  price: 2820,
  tier: 5.043636,
  requirement: 0,
  weight: 11.6,
  flags: ['ForceAttachOffHandSecondaryItemBone', 'WoodenParry', 'HeldInOffHand'],
  armor: null,
  mount: null,
  weapons: [
    {
      class: 'LargeShield',
      itemUsage: 'shield',
      accuracy: 100,
      missileSpeed: 0,
      stackAmount: 70,
      length: 132,
      balance: 0,
      handling: 82,
      bodyArmor: 0,
      flags: ['HasHitPoints', 'CanBlockRanged'],
      thrustDamage: 0,
      thrustDamageType: 'Blunt',
      thrustSpeed: 82,
      swingDamage: 0,
      swingDamageType: 'Blunt',
      swingSpeed: 82,
    },
  ],
};

export const Bow = {
  id: 'crpg_noble_bow',
  baseId: 'crpg_noble_bow',
  createdAt: '2023-07-13T21:43:44.0741909Z',
  rank: 0,
  name: 'Noble Bow',
  culture: 'Neutral',
  type: 'Bow',
  price: 12133,
  tier: 9.940793,
  requirement: 0,
  weight: 0.4,
  flags: ['ForceAttachOffHandPrimaryItemBone'],
  armor: null,
  mount: null,
  weapons: [
    {
      class: 'Bow',
      itemUsage: 'bow',
      accuracy: 95,
      missileSpeed: 85,
      stackAmount: 1,
      length: 116,
      balance: 0,
      handling: 100,
      bodyArmor: 0,
      flags: [
        'RangedWeapon',
        'NotUsableWithOneHand',
        'HasString',
        'StringHeldByHand',
        'UnloadWhenSheathed',
        'AutoReload',
        'TwoHandIdleOnMount',
      ],
      thrustDamage: 14,
      thrustDamageType: 'Pierce',
      thrustSpeed: 100,
      swingDamage: 0,
      swingDamageType: 'Blunt',
      swingSpeed: 98,
    },
  ],
};

export const Bolts = {
  id: 'crpg_bolt_f',
  baseId: 'crpg_bolt_f',
  createdAt: '2023-07-13T21:43:44.0741909Z',
  rank: 0,
  name: 'Heavy Piercing Bolts',
  culture: 'Empire',
  type: 'Bolts',
  price: 7815,
  tier: 9.736687,
  requirement: 0,
  weight: 0.3,
  flags: ['ForceAttachOffHandPrimaryItemBone'],
  armor: null,
  mount: null,
  weapons: [
    {
      class: 'Bolt',
      itemUsage: '',
      accuracy: 100,
      missileSpeed: 10,
      stackAmount: 5,
      length: 37,
      balance: 0,
      handling: 0,
      bodyArmor: 0,
      flags: ['AttachAmmoToVisual', 'Consumable'],
      thrustDamage: 14,
      thrustDamageType: 'Pierce',
      thrustSpeed: 0,
      swingDamage: 0,
      swingDamageType: 'Blunt',
      swingSpeed: 0,
    },
  ],
};

export const ThrowingAxe = {
  id: 'crpg_western_throwing_axe_1_t1',
  baseId: 'crpg_western_throwing_axe_1_t1',
  createdAt: '2023-07-13T21:43:44.0741909Z',
  rank: 0,
  name: 'Francesca',
  culture: 'Vlandia',
  type: 'Thrown',
  price: 2300,
  tier: 5.093825,
  requirement: 0,
  weight: 1.25,
  flags: ['CanBePickedUpFromCorpse'],
  armor: null,
  mount: null,
  weapons: [
    {
      class: 'OneHandedAxe',
      itemUsage: 'onehanded_shield_axe',
      accuracy: 0,
      missileSpeed: 0,
      stackAmount: 0,
      length: 38,
      balance: 1,
      handling: 108,
      bodyArmor: 0,
      flags: ['MeleeWeapon', 'BonusAgainstShield'],
      thrustDamage: 0,
      thrustDamageType: 'Undefined',
      thrustSpeed: 94,
      swingDamage: 11,
      swingDamageType: 'Cut',
      swingSpeed: 111,
    },
    {
      class: 'ThrowingAxe',
      itemUsage: 'throwing_axe',
      accuracy: 93,
      missileSpeed: 25,
      stackAmount: 3,
      length: 38,
      balance: 1,
      handling: 108,
      bodyArmor: 0,
      flags: [
        'RangedWeapon',
        'Consumable',
        'UnloadWhenSheathed',
        'BonusAgainstShield',
        'AutoReload',
        'AmmoBreaksOnBounceBack',
      ],
      thrustDamage: 32,
      thrustDamageType: 'Undefined',
      thrustSpeed: 94,
      swingDamage: 0,
      swingDamageType: 'Cut',
      swingSpeed: 111,
    },
  ],
};

export const MountHarness = {
  id: 'crpg_light_harness',
  baseId: 'crpg_light_harness',
  createdAt: '2023-07-13T21:43:44.0741909Z',
  rank: 0,
  name: 'Light Harness',
  culture: 'Neutral',
  type: 'MountHarness',
  price: 1712,
  tier: 1.3333334,
  requirement: 0,
  weight: 20,
  flags: ['Civilian'],
  armor: {
    headArmor: 0,
    bodyArmor: 6,
    armArmor: 0,
    legArmor: 0,
    materialType: 'Leather',
    familyType: 1,
  },
  mount: null,
  weapons: [],
};

export const Mount = {
  id: 'crpg_mount_balanced_5',
  baseId: 'crpg_mount_balanced_5',
  createdAt: '2023-07-13T21:43:44.0741909Z',
  rank: 0,
  name: 'Murgese Rouncey',
  culture: 'Khuzait',
  type: 'Mount',
  price: 5384,
  tier: 4.998832,
  requirement: 0,
  weight: 450,
  flags: ['Civilian'],
  armor: null,
  mount: {
    bodyLength: 105,
    chargeDamage: 1,
    maneuver: 66,
    speed: 40,
    hitPoints: 172,
    familyType: 1,
  },
  weapons: [],
};

export const Helmet = {
  id: 'crpg_sa_1ChurburghHelm',
  baseId: 'crpg_sa_1ChurburghHelm',
  createdAt: '2023-07-13T21:43:44.0741909Z',
  rank: 0,
  name: 'Hounskull Bascinet',
  culture: 'Vlandia',
  type: 'HeadArmor',
  price: 14334,
  tier: 9.969065,
  requirement: 0,
  weight: 4.64,
  flags: [],
  armor: {
    headArmor: 64,
    bodyArmor: 0,
    armArmor: 0,
    legArmor: 0,
    materialType: 'Plate',
    familyType: 0,
  },
  mount: null,
  weapons: [],
};
