---
- name: Install PostgreSQL
  apt:
    name:
    - python3-psycopg2
    - acl # needed by postgresql_user module (https://github.com/georchestra/ansible/issues/55#issuecomment-588313638)
    - postgresql
    - postgresql-client

- name: Gather package facts
  package_facts:

- name: Extract PostgreSQL major version
  set_fact:
    postgresql_version_major: "{{ ansible_facts.packages['postgresql'][0].version.split('-')[0].split('+')[0] }}"

- name: Install geographic objects support for PostgreSQL
  apt:
    name:
    - postgis
    - "postgresql-{{ postgresql_version_major }}-postgis-3"

- name: Create PostgreSQL configuration file
  template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version_major }}/main/postgresql.conf"
    mode: 0644

- name: Ensure PostgreSQL is started
  service:
    name: postgresql
    state: started

- name: Create cRPG PostgreSQL user
  become_user: postgres
  postgresql_user:
    name: "{{ crpg_db_user }}"
    password: "{{ crpg_db_user_password }}"

- name: Create cRPG PostgreSQL database
  become_user: postgres
  postgresql_db:
    name: "{{ crpg_db }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8

- name: Enable geographic objects support for cRPG database
  become_user: postgres
  postgresql_ext:
    name: postgis
    db: "{{ crpg_db }}"

- name: Create Datadog PostgreSQL user
  become_user: postgres
  postgresql_user:
    name: "{{ datadog_db_user }}"
    groups: pg_monitor

- name: Create a schema for Datadog in cRPG database
  become_user: postgres
  postgresql_schema:
    name: datadog
    owner: "{{ datadog_db_user }}"
    db: "{{ crpg_db }}"

- name: Enable pg_stat_statements module
  become_user: postgres
  postgresql_ext:
    name: pg_stat_statements
    db: "{{ crpg_db }}"

- name: Upload explain_statement function
  template:
    src: explain_statement.sql.j2
    dest: /tmp/explain_statement.sql
    mode: 0644

- name: Create explain_statement function
  become_user: postgres
  postgresql_db:
    db: "{{ crpg_db }}"
    target: /tmp/explain_statement.sql

- name: Grant Datadog user SELECT permission on cRPG database
  become_user: postgres
  postgresql_privs:
    database: "{{ crpg_db }}"
    privs: SELECT
    objs: ALL_IN_SCHEMA
    role: "{{ datadog_db_user }}"

- name: Disable logging for Datadog user in cRPG database
  become_user: postgres
  postgresql_query:
    db: "{{ crpg_db }}"
    query: "ALTER ROLE \"{{ datadog_db_user }}\" SET log_min_duration_statement = -1"

- name: Restart PostgreSQL
  service:
    name: postgresql
    enabled: yes
    state: restarted
