namespace Crpg.Domain.Entities.Items
{
    public enum WeaponClass
    {
        Undefined,
        Dagger,
        OneHandedSword,
        TwoHandedSword,
        OneHandedAxe,
        TwoHandedAxe,
        Mace,
        Pick,
        TwoHandedMace,
        OneHandedPolearm,
        TwoHandedPolearm,
        LowGripPolearm,
        Arrow,
        Bolt,
        Cartridge,
        Bow,
        Crossbow,
        Stone,
        Boulder,
        ThrowingAxe,
        ThrowingKnife,
        Javelin,
        Pistol,
        Musket,
        SmallShield,
        LargeShield,
        Banner,
    }
}
